sudo: required

before_install:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generation
  - gem install asciidoctor-pdf --pre # PDF generation

script:
  - asciidoctor tpgl.adoc -o tp.html

after_success:
  - echo Done!

